export const MIME_TO_EXTENSION = {
  "application/atom+xml": "atom",
  "application/epub+zip": "epub",
  "application/gzip": "gz",
  "application/json": "json",
  "application/ld+json": "jsonld",
  "application/msword": "doc",
  "application/octet-stream": "bin",
  "application/pdf": "pdf",
  "application/pkcs7-mime": "p7m",
  "application/pkcs8": "p8",
  "application/postscript": "ps",
  "application/rtf": "rtf",
  "application/vnd.amazon.ebook": "azw",
  "application/vnd.android.package-archive": "apk",
  "application/vnd.apple.installer+xml": "mpkg",
  "application/vnd.apple.pkpass": "pkpass",
  "application/vnd.google-apps.audio": "gdaudio",
  "application/vnd.google-apps.document": "gdoc",
  "application/vnd.google-apps.drawing": "gdraw",
  "application/vnd.google-apps.drive-sdk": "gdrive-sdk",
  "application/vnd.google-apps.file": "gfile",
  "application/vnd.google-apps.folder": "gfolder",
  "application/vnd.google-apps.form": "gform",
  "application/vnd.google-apps.fusiontable": "gtable",
  "application/vnd.google-apps.jam": "gjam",
  "application/vnd.google-apps.map": "gmap",
  "application/vnd.google-apps.photo": "gphoto",
  "application/vnd.google-apps.presentation": "gslides",
  "application/vnd.google-apps.script": "gscript",
  "application/vnd.google-apps.shortcut": "gshortcut",
  "application/vnd.google-apps.site": "gsite",
  "application/vnd.google-apps.spreadsheet": "gsheet",
  "application/vnd.google-apps.video": "gvideo",
  "application/vnd.ms-excel": "xls",
  "application/vnd.ms-excel.sheet.macroenabled.12": "xlsm",
  "application/vnd.ms-powerpoint": "ppt",
  "application/vnd.ms-powerpoint.presentation.macroenabled.12": "pptm",
  "application/vnd.ms-word.document.macroenabled.12": "docm",
  "application/vnd.oasis.opendocument.chart": "odc",
  "application/vnd.oasis.opendocument.database": "odb",
  "application/vnd.oasis.opendocument.formula": "odf",
  "application/vnd.oasis.opendocument.graphics": "odg",
  "application/vnd.oasis.opendocument.presentation": "odp",
  "application/vnd.oasis.opendocument.spreadsheet": "ods",
  "application/vnd.oasis.opendocument.text": "odt",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation":
    "pptx",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
    "docx",
  "application/vnd.rar": "rar",
  "application/vnd.visio": "vsd",
  "application/wasm": "wasm",
  "application/x-7z-compressed": "7z",
  "application/x-bittorrent": "torrent",
  "application/x-bzip": "bz",
  "application/x-bzip2": "bz2",
  "application/x-cdf": "cdf",
  "application/x-csh": "csh",
  "application/x-debian-package": "deb",
  "application/x-freearc": "arc",
  "application/x-gtar": "gtar",
  "application/x-httpd-php": "php",
  "application/x-msdownload": "exe",
  "application/x-sh": "sh",
  "application/x-shockwave-flash": "swf",
  "application/x-tar": "tar",
  "application/x-www-form-urlencoded": "urlencoded",
  "application/x-x509-ca-cert": "crt",
  "application/x-yaml": "yaml",
  "application/xml": "xml",
  "application/zip": "zip",
  "audio/aac": "aac",
  "audio/flac": "flac",
  "audio/midi": "midi",
  "audio/mp4": "m4a",
  "audio/mpeg": "mp3",
  "audio/ogg": "oga",
  "audio/opus": "opus",
  "audio/wav": "wav",
  "audio/webm": "weba",
  "audio/x-m4a": "m4a",
  "audio/x-wav": "wav",
  "font/collection": "ttc",
  "font/otf": "otf",
  "font/ttf": "ttf",
  "font/woff": "woff",
  "font/woff2": "woff2",
  "image/avif": "avif",
  "image/bmp": "bmp",
  "image/gif": "gif",
  "image/heic": "heic",
  "image/heif": "heif",
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/svg+xml": "svg",
  "image/tiff": "tiff",
  "image/vnd.microsoft.icon": "ico",
  "image/webp": "webp",
  "image/x-icon": "ico",
  "model/gltf+json": "gltf",
  "model/gltf-binary": "glb",
  "model/obj": "obj",
  "model/stl": "stl",
  "text/calendar": "ics",
  "text/csv": "csv",
  "text/markdown": "md",
  "text/plain": "txt",
  "text/tab-separated-values": "tsv",
  "text/vcard": "vcf",
  "text/vtt": "vtt",
  "text/xml": "xml",
  "video/3gpp": "3gp",
  "video/mp2t": "ts",
  "video/mp4": "mp4",
  "video/mpeg": "mpeg",
  "video/ogg": "ogv",
  "video/quicktime": "mov",
  "video/webm": "webm",
  "video/x-flv": "flv",
  "video/x-matroska": "mkv",
  "video/x-msvideo": "avi",
} as const;

export type SupportedMimeType = keyof typeof MIME_TO_EXTENSION;

export function isValidMimeType(
  mimeType: string,
): mimeType is keyof typeof MIME_TO_EXTENSION {
  return mimeType in MIME_TO_EXTENSION;
}

export function mimeToExtension(
  mimeType: keyof typeof MIME_TO_EXTENSION,
): string {
  return MIME_TO_EXTENSION[mimeType];
}
